name: 'Get & Cache Dependencies'
description: 'for yarn berry'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: npm install -g corepack && corepack enable
      shell: bash
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install
      shell: bash
