name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Enable Corepack
        run: npm install -g corepack && corepack enable
      - name: Install dependencies
        run: yarn install --immutable

      - name: Check Lint
        run: yarn lint

      - name: Check Unit Test
        run: yarn test
